### ISSUE TITLE
Give credit to Robb Owen

### ISSUE THREAD

**Issue by hellosputnik** [ajshortt/tokyo-hack#1]
Your project was heavily inspired by @robb0wen's [synthwave theme](https://github.com/robb0wen/synthwave-vscode) and your initial publish of v0.3.0 actually included some of his assets. You should include Robb's original license without modifications per the MIT license.

https://marketplace.visualstudio.com/items?itemName=alex-shortt.tokyo-hack#review-details has [Robb's banner](https://github.com/robb0wen/synthwave-vscode/raw/master/banner.png).

**Comment by ajshortt** [comment]
Thanks @hellosputnik. I've been meaning to change this 👍

**Comment by ajshortt** [comment]
Thanks @hellosputnik.
Agreed, Robb's Synthwave theme has played a large part in the inspiration for this project and it was used as an early starting point whilst this project was in it's earliest stages. I have added a credit section to the README thanking Robb and recommending the Synthwave theme. 

As for the licence, Robbs assets were wrongly committed to an older release and again, whilst inspiring a lot of this project and used as a playground for this project, the official code for this project is completely different. With that said, the licence will remain the same. 

Once again, thanks for your input 👍

**Comment by hellosputnik** [comment]
Great!
